package com.hassan;
// Generated Jan 10, 2023, 8:08:58 PM by Hibernate Tools 6.1.6.Final


import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="inheritance2"
)
public class Student extends Person {

     private String department;

    public Student() {
    }

    public Student(String firstName, String lastName, String department) {
       super( firstName , lastName);
       this.department = department;
    }
   
//     @Id
//
//
//    @Column(name="id", unique=true, nullable=false)
//    public int getId() {
//        return this.id;
//    }
//
//    public void setId(int id) {
//        this.id = id;
//    }
//
//
//    @Column(name="first_name", nullable=false, length=50)
//    public String getFirstName() {
//        return this.firstName;
//    }
//
//    public void setFirstName(String firstName) {
//        this.firstName = firstName;
//    }
//
//
//    @Column(name="last_name", nullable=false, length=50)
//    public String getLastName() {
//        return this.lastName;
//    }
//
//    public void setLastName(String lastName) {
//        this.lastName = lastName;
//    }
//
//
    @Column(name="department", nullable=false, length=45)
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }




}


