package com.hassan;
// Generated Jan 10, 2023, 8:08:58 PM by Hibernate Tools 6.1.6.Final


import jakarta.persistence.*;
import java.util.Date;

/**
 * Teacher generated by hbm2java
 */

@Table(name="teacher"
    ,catalog="inheritance2"
)
@Entity
@DiscriminatorValue("TA")
public class Teacher  extends Person {

     private Date hireDate;

    public Teacher() {
    }

    public Teacher(String firstName, String lastName, Date hireDate) {
       super(firstName , lastName);
       this.hireDate = hireDate;
    }
   
//    @Id
//
//
//    @Column(name="id", unique=true, nullable=false)
//    public int getId() {
//        return this.id;
//    }
//
//    public void setId(int id) {
//        this.id = id;
//    }
//
//
//    @Column(name="first_name", nullable=false, length=50)
//    public String getFirstName() {
//        return this.firstName;
//    }
//
//    public void setFirstName(String firstName) {
//        this.firstName = firstName;
//    }
//
//
//    @Column(name="last_name", nullable=false, length=50)
//    public String getLastName() {
//        return this.lastName;
//    }
//
//    public void setLastName(String lastName) {
//        this.lastName = lastName;
//    }

    @Temporal(TemporalType.DATE)
    @Column(name="hire_date", nullable=false, length=10)
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }




}


