package com.hassan;


import jakarta.persistence.*;

/**
 * Person generated by hbm2java
 */

@Table(name="person"
    ,catalog="inheritance4"
)
@Entity
@Inheritance(strategy=InheritanceType.JOINED)
public class Person  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String lastName;
     private String personType;

    public Person() {
    }

	
    public Person( String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }
    public Person(String firstName, String lastName, String personType) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.personType = personType;
    }
   
  
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="first_name", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="person_type", length=45)
    public String getPersonType() {
        return this.personType;
    }
    
    public void setPersonType(String personType) {
        this.personType = personType;
    }

}


