package com.hassan;

// Generated Jan 10, 2023, 10:06:40 PM by Hibernate Tools 6.1.6.Final

import jakarta.persistence.*;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "inheritance4")
public class Student extends Person {
    private String department;

    public Student() {
    }

    public Student(String department, String firstName, String lastName) {
        super(firstName, lastName, "Student");
        this.department = department;
    }

    @Column(name = "department", nullable = false, length = 45)
    public String getDepartment() {
        return this.department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

}
