package com.hassan;
// Generated Jan 10, 2023, 10:06:40 PM by Hibernate Tools 6.1.6.Final

import jakarta.persistence.*;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.Date;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "inheritance4")
public class Teacher extends Person {

    private int id;
    private Date hireDate;

    public Teacher() {
    }

    public Teacher(String firstName, String lastName, Date hireDate ) {
        super(firstName, lastName , "Teacher");
        this.hireDate = hireDate;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "hire_date", nullable = false, length = 10)
    public Date getHireDate() {
        return this.hireDate;
    }

    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

}
