package com.hassan;
// Generated Jan 10, 2023, 1:16:17 PM by Hibernate Tools 6.1.6.Final


import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * Person generated by hbm2java
 */
@Entity
@MappedSuperclass
public abstract class Person implements java.io.Serializable {

    private String firstName;
    private String lastName;

    public Person() {
    }

    public Person(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    @Column(name = "first_name", nullable = true, length = 50)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }


    @Column(name = "last_name", nullable = true, length = 50)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}


