package com.hassan;
// Generated Jan 10, 2023, 1:16:17 PM by Hibernate Tools 6.1.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;

import static jakarta.persistence.GenerationType.IDENTITY;

import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import java.time.LocalDate;
import java.util.Date;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher"
        , catalog = "inheritance1"
)
public class Teacher extends Person {


    private Integer id;
    private String firstName;
    private String lastName;
    private LocalDate hireDate;

    public Teacher() {
    }

    public Teacher(String firstName, String lastName, LocalDate hireDate) {
        super(firstName, lastName);
        this.firstName = firstName;
        this.lastName = lastName;
        this.hireDate = hireDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


//    @Column(name="first_name", nullable=false, length=50)
//    public String getFirstName() {
//        return this.firstName;
//    }

//    public void setFirstName(String firstName) {
//        this.firstName = firstName;
//    }


//    @Column(name="last_name", nullable=false, length=50)
//    public String getLastName() {
//        return this.lastName;
//    }
//
//    public void setLastName(String lastName) {
//        this.lastName = lastName;
//    }

    @Temporal(TemporalType.DATE)
    @Column(name = "hire_date", nullable = false, length = 10)
    public LocalDate getHireDate() {
        return this.hireDate;
    }

    public void setHireDate(LocalDate hireDate) {
        this.hireDate = hireDate;
    }


}


